import streamlit as st
import requests
import json
from pages.config import API_BASE_URL

st.title("🤖 Step 4: LLM Interpretation")

if not st.session_state.get("xai_results") or not st.session_state.get("detection_result"):
    st.warning("Please generate XAI explanations first.")
    st.stop()

st.markdown("""
Using **Ollama**, we will now translate the mathematical XAI metrics into a human-readable forensic report.
""")

st.sidebar.markdown("### LLM Configuration")
available_models = ["llama3.1:8b-instruct-q4_K_M"]
try:
    res = requests.get(f"{API_BASE_URL}/api/v1/interpret/status")
    if res.status_code == 200:
        data = res.json()
        if data.get("status") and "models" in data:
            available_models = data["models"]
except Exception:
    pass

selected_llm = st.sidebar.selectbox("Select Ollama Model", available_models)

# Use the first result's XAI ID for the cache key
first_result = st.session_state.xai_results[0]
detection_id = st.session_state.get("detection_id")
xai_result_id = first_result.get("xai_result_id")

payload = {
    "detector_name": st.session_state.model_name,
    "explainer_name": first_result["explainer"],
    "ai_deepfake": st.session_state.detection_result["label"] == "Deepfake",
    "confidence": st.session_state.detection_result["confidence"],
    "metrics": first_result["metrics"],
    "llm_model": selected_llm,
    "detection_id": detection_id,
    "xai_result_id": xai_result_id,
}

# ─── Check cache before showing button ────────────────────────────────────────
is_cached = False
if detection_id and xai_result_id:
    try:
        cache_res = requests.get(
            f"{API_BASE_URL}/api/v1/interpret/cached",
            params={
                "detection_id": detection_id,
                "xai_result_id": xai_result_id,
                "llm_model": selected_llm,
            },
        ).json()
        is_cached = cache_res.get("cached", False)
    except Exception:
        pass

col_btn, col_badge = st.columns([3, 1])

with col_badge:
    if is_cached:
        st.success("📦 Cached")
        st.caption("Response was loaded from DB — instant!")

with col_btn:
    btn_label = "Load Cached Report ⚡" if is_cached else "Generate Forensic Report"
    generate_btn = st.button(btn_label, type="primary")
    if is_cached:
        force_regen = st.button("🔄 Regenerate (new LLM call)", type="secondary")
    else:
        force_regen = False

if generate_btn or force_regen:
    # If forcing regeneration, clear cache key so interpret.py won't hit cache
    if force_regen:
        payload_to_send = {**payload, "detection_id": None, "xai_result_id": None}
        spinner_msg = "Regenerating with Ollama (this will overwrite the cached response)..."
    else:
        payload_to_send = payload
        spinner_msg = "Loading cached report from DB..." if is_cached else "Connecting to local Llama 3.1..."

    with st.spinner(spinner_msg):
        try:
            response = requests.post(
                f"{API_BASE_URL}/api/v1/interpret",
                json=payload_to_send,
                stream=True,
            )

            if response.status_code == 200:
                cache_status = response.headers.get("X-Cache", "UNKNOWN")
                if cache_status == "HIT":
                    st.info("⚡ Response served from SQLite cache — no Ollama call was made.")
                elif cache_status == "MISS":
                    st.info("🧠 Fresh response generated by Ollama and saved to cache.")

                st.markdown("### Forensic Analysis Report")

                def generate():
                    for chunk in response.iter_content(chunk_size=1024):
                        if chunk:
                            yield chunk.decode("utf-8")

                st.write_stream(generate())
            else:
                st.error(f"Error: {response.text}")

        except Exception as e:
            st.error(f"Failed to connect to LLM endpoint: {e}")
            st.info("Make sure 'ollama serve' is running in the background!")

if st.button("🏠 Return Home"):
    st.switch_page("pages/1_Home.py")
